### ISSUE TITLE
Fails if schema.rs moved

### ISSUE THREAD

**Issue by brianmay** [adwhit/diesel-derive-enum#101]
I tried to move `schema.rs` from `src/schema.rs` to `src/server/schema.rs` but now I get this confusing error:

```rust
error[E0433]: failed to resolve: unresolved import
  --> src/model.rs:10:39
   |
10 | #[cfg_attr(feature = "server", derive(diesel_derive_enum::DbEnum, Debug))]
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ unresolved import
   |
   = help: consider importing this module:
           crate::server::schema::sql_types
   = note: this error originates in the derive macro `diesel_derive_enum::DbEnum` (in Nightly builds, run with -Z macro-backtrace for more info)
 ```

The error makes it appear that it can't resolve `DbEnum`, but as the bottom line states the error is happening inside the macro.

**Comment by brianmay** [comment]
Find code here: https://github.com/brianmay/dioxus-fs-demo/pull/1

**Comment by adwhit** [comment]
Looks like you didn't update `ExistingTypePath` on line 13

**Comment by brianmay** [comment]
You are probably right. Thanks for your help. Closing.
