### ISSUE TITLE
DbEnum doesn't seem to have an effect for integer-based enums

### ISSUE THREAD

**Issue by ghost** [adwhit/diesel-derive-enum#26]
I have an enum roughly like this:
```
#[derive(Clone, Copy, DbEnum, Debug, Deserialize, Diff, PartialEq, Serialize)]
    pub enum MyType {
        A = 0,
        B = 1,
        C = 2,
    }
```

Yet when I attempt to use it, I get this:
```
the trait `diesel::Queryable<diesel::sql_types::Integer, _>` is not implemented for `MyType`
```

Thanks.

**Comment by adwhit** [comment]
Hmm, I am not sure how this would work. Would you like to store them as integers and retrieve them as enums, or vice versa? Could you post some code showing how you are trying to use it?

**Comment by pmi-spease** [comment]
Right. I've been perpetually confused by diesel's traits (I wish they were as straightforward as serde's deserialize), but I believe it would look something like this with enum-primitive-derive:

```#[derive(Clone, Copy, DbEnum, Debug, Deserialize, Diff, PartialEq, Primitive, Serialize)]
    pub enum MyType {
        A = 0,
        B = 1,
        C = 2,
    }

impl ::diesel::deserialize::FromSqlRow<::diesel::sql_types::Integer, ::diesel::sqlite::Sqlite> for MyType {
	    fn build_from_row<R: ::diesel::row::Row<::diesel::sqlite::Sqlite>>(row: &mut R) -> Result<Self, Box<std::error::Error+Send+Sync>> {
	    	Ok(MyType::from_i32(i32::build_from_row(row)?))
	    }
	}```

**Comment by adwhit** [comment]
Right, so you're trying to turn a column of integers into enums. That's not how this crate works, it is designed to store values as an ENUM type.

I think what you're asking for should be possible but I think it's a bit niche. Would it be better just to convert to `MyType` after loading the integers?

**Comment by behos** [comment]
Since you have raised a similar issue to my implementation of the DBEnum, there are only 2 traits you need to implement for your enum. (And you should base it on existing types, in your case Int4)

```
impl FromSql<Int4, Pg> for MyType

impl ToSql<Int4, Pg> for MyType
```

With these implemented, you can then derive

```
#[derive(FromSqlRow, AsExpression)]
```
on your enum type and this should be all you need.

**Comment by pmi-spease** [comment]
Thanks. I think maybe the confusion here is that I'm working with sqlite. However I was able to find this:
// https://stackoverflow.com/questions/49092437/how-do-i-implement-queryable-and-insertable-for-custom-field-types-in-diesel

For which I came up with:
```
impl<DB: Backend> FromSql<diesel::sql_types::Integer, DB> for MyEnum where i32: FromSql<diesel::sql_types::Integer, DB> {
        fn from_sql(bytes: Option<&DB::RawValue>) -> diesel::deserialize::Result<Self> {
            let v = i32::from_sql(bytes)?;
            Ok(MyEnum::from_i32(v).ok_or_else(||format_err!("Unknown MyEnum {}", v))?)
        }
    }

impl<DB: Backend> FromSql<diesel::sql_types::Text, DB> for MyOtherType where String: FromSql<diesel::sql_types::Text, DB> {
        fn from_sql(bytes: Option<&DB::RawValue>) -> diesel::deserialize::Result<Self> {
            let v = String::from_sql(bytes)?;
            Ok(v.parse()?)
        }
    }
```

Which at least compiles, although I haven't tested it yet. It's just a bit tedious / mechanical to do this for each enum, and I was hoping I could use a simple derive (eg DbEnumInteger / DbEnumString).

**Comment by behos** [comment]
You can probably get away with a declarative macro for your project to avoid having to write the whole thing every time:

```
    macro int_enum($type:ident) {

        impl<DB: Backend> FromSql<Integer, DB> for $type
        where
            i32: FromSql<diesel::sql_types::Integer, DB>,
        {
            fn from_sql(bytes: Option<&DB::RawValue>) -> Result<Self> {
                let val = i32::from_sql(bytes)?;
                Ok($type::from_i32(val).expect("Uh oh! Throw a real error here"))
            }
        }

        impl<DB: Backend> ToSql<Integer, DB> for $type
        where
            i32: ToSql<diesel::sql_types::Integer, DB>,
        {
            fn to_sql<W: Write>(&self, out: &mut Output<W, DB>) -> SerResult {
                i32::to_sql(&(*self as i32), out)
            }
        }
    }

    int_enum!(MyType);
    int_enum!(MyOtherType);
```
