### ISSUE TITLE
Why do you have table macro in the code?

### ISSUE THREAD

**Issue by viktor-ku** [adwhit/diesel-derive-enum#27]
Hi. Isn't the `table!` macro should be auto generated by the diesel? And if so then how to "inject" custom `enum`s there. Right now I am getting the error from the `schema.rs` saying:

> cannot find type `Lang_enum` in this scope

Please help!
Thanks in advance

**Comment by adwhit** [comment]
Hi,

No, the table macro is not auto-generated by diesel. It *can* be generated by Diesel's `infer_schema!` macro, but as noted in the `README`, it is not compatible with this crate. You'll need to use the `table!` macro explicitly.

**Comment by viktor-ku** [comment]
Would you suggest keeping the `table!` close to the model or in the separate file? I understood my problem, but just asking for your advice regarding the structure.

Thanks

**Comment by adwhit** [comment]
Very much a matter of taste. I have tended to have `model.rs` and `schema.rs` in adjacent files. E.g. take a look at the layout in the [diesel examples](https://github.com/diesel-rs/diesel/tree/77be57f111e75e9ce4dcd0cba3fdf86c20c3d9bc/examples/postgres/getting_started_step_1/src)

**Comment by viktor-ku** [comment]
Thank you!
