### ISSUE TITLE
Document use with infer_schema!

### ISSUE THREAD

**Issue by adwhit** [adwhit/diesel-derive-enum#3]
infer_schema! will "guess" the name of the mapping type, which won't match up with that generated by the macro. Give an example/explanation of this

**Comment by adwhit** [comment]
I'm not sure if this can actually work with `infer_schema!` since diesel might not be able to import our custom derived type into the module even if the mapping names match. Will need an actual test.

**Comment by Eijebong** [comment]
Nope, you can't use custom types with `infer_schema!`, you have to use `diesel print-schema` for that.

**Comment by JeanMertz** [comment]
> you have to use diesel print-schema for that.

To add to this, I'm assuming that this will actually not work with Sqlite, as it doesn't have a custom `ENUM` type, and simply adds a condition to the `TEXT` type?

> The `print-schema` command (from `diesel_cli`) attempts to connect to an existing DB and generate a correct mapping of Postgres columns to Diesel internal types. If a custom ENUM exists in the database, Diesel will simply assume that the internal mapping type is the ENUM name

**Comment by adwhit** [comment]
This library doesn't work with `infer_schema!` and I don't think that will ever change.
