### ISSUE TITLE
Compatibility with Diesel's master branch

### ISSUE THREAD

**Issue by Ten0** [adwhit/diesel-derive-enum#30]
The current master branch is not compatible with Diesel's master branch (a few minor changes to apply so that it is).

I've pushed a commit to make it compatible on [this fork](https://github.com/Ten0/diesel-derive-enum).
I'd like to create a pull request but this is probably not suitable for your master branch because that would break on the current crates.io version of diesel, so it would be better to use a separate branch.

Can you create a new branch (`diesel-master-compatible` or similar) so I can open the PR ?

**Comment by adwhit** [comment]
Hi, thanks for the head's up. I think it should be fine to issue a PR directly against master. I don't have to issue a release until diesel does likewise.

**Comment by Ten0** [comment]
OK :)
