### ISSUE TITLE
Cannot 'insert_into()' with sqlite CHECK constraint

### ISSUE THREAD

**Issue by rjloura** [adwhit/diesel-derive-enum#33]
I have the following simple struct and enum:
```rs
#[derive(DbEnum, Debug, PartialEq, Clone)]
pub enum ObjectStatus {
    Unprocessed,
    Processing,
    Skipped,
    Failed,
    Retrying,
}

#[derive(Insertable, Queryable, Identifiable, Debug, PartialEq)]
#[table_name = "evacuateobjects"]
pub struct Object {
    pub id: i32,
    pub status: ObjectStatus,
}
```

If I create the table like so:
```rs
    conn.execute(
        r#"
        CREATE TABLE evacuateobjects(
            id SERIAL PRIMARY KEY,
            status TEXT CHECK(status IN ('Unprocessed', 'Processing', 'Skipped', 'Failed', 'Retrying')) NOT NULL
        );
    "#,
    ).unwrap();
```

Any inserts fail with `DatabaseError(__Unknown, "CHECK constraint failed: evacuateobjects")'`

If I remove the CHECK constraint (`status TEXT NOT NULL`) everything works out just fine.
```
    let items = evacuateobjects::table.load::<Object>(conn).unwrap();
    assert_eq!(items[0].status, ObjectStatus::Skipped);
```

Oddly the sqlite enum round trip test passes just fine on the same system.

**Comment by adwhit** [comment]
A guess: the `check` strings should be `snake_cased` i.e. `'unprocessed`, 'processing'` etc.

**Comment by rjloura** [comment]
That's it.  Changed all the sql representations to `snake_case` and it worked.

I see a comment on the Postgres section now.  I suppose I glossed over that and went straight to the sqlite section.

**Comment by adwhit** [comment]
Fair point. Added a quick note to the examples.
