### ISSUE TITLE
want support for enum variants with fields

### ISSUE THREAD

**Issue by rjloura** [adwhit/diesel-derive-enum#39]
Using this crate with an sqlite database.

This works great:
```rs
#[derive(Insertable, Queryable, Identifiable, Debug, PartialEq)]
#[table_name = "evacuateobjects"]
pub struct EvacuateObjectDB {
    pub id: String,
    pub status: EvacuateObjectStatus,
}

#[derive(DbEnum, Debug, PartialEq, Clone)]
pub enum EvacuateObjectStatus {
    Unprocessed,
    Processing,
    Skipped,
    Failed,
    Retrying,
}
```

But this:
```rs
#[derive(Insertable, Queryable, Identifiable, Debug, PartialEq)]
#[table_name = "evacuateobjects"]
pub struct EvacuateObjectDB {
    pub id: String,
    pub status: EvacuateObjectStatus,
}

#[derive(DbEnum, Debug, PartialEq, Clone)]
pub enum SkippedReason {
    Retry,
    Persistent,
}
#[derive(DbEnum, Debug, PartialEq, Clone)]
pub enum EvacuateObjectStatus {
    Unprocessed,
    Processing,
    Skipped(SkippedReason),
    Failed,
    Retrying,
}
```
Gives the error: "Variants must be fieldless"

Would be nice if something like `EvacuateObjectStatus::Skipped(SkippedReason::Retry)` could be mapped to a string `skipped:retry`.

**Comment by adwhit** [comment]
Nice idea but difficult to see how it could actually be implemented. If you have a PR I would consider it, otherwise I would recommend just doing that impls manually.

**Comment by rjloura** [comment]
Thinking about it a bit more... I'm not sure there is a good use case for this because in the case where one would have nested enums one would probably want to use associations to a static table with joins.  

But initially I was thinking something like:
```rs
enum ErrorCode {
  NoSpace,
  NoMem,
  Other,
}

enum Status {
  Init,
  Finished,
  Error(ErrorCode),
}
```
Which would map to a text/varchar field with some delimiter (e.g. `:`) something like:
```
status:error:no_space
```

This kind of assumes that the implementer wouldn't want to query on the parent enum (e.g. `select * from records where status = 'error'`).  Or one could use a `WHERE column LIKE <val>` clause, but that's a bit brittle. 

I went ahead and coded up a one off of this, but I've decided to go a different direction for my work.
https://gist.github.com/rjloura/704f71a519b0a849275b24ecc2a65838

**Comment by adwhit** [comment]
Out of scope

**Comment by weilbith** [comment]
Hey 👋 
Sorry, I'm completely new to Diesel and this topic. But I'm here with this exact use-case:

I want to represent a data structure concept using rust enum variants with structs:

```rust
enum Foo {
   Bar { value: String, order i64 },
  Baz { something: bool, order: i64 }
}
```

I would now like to have two tables for `Bar` and `Baz`. How would I do this with Diesel (and this library)?

**Comment by adwhit** [comment]
The short answer is - you can't, because relational databases don't allow you to store sum-types in the way you want.

The longer answer is - you would have to use a table with three columns - `order`, `value` and `something` - and make value and something nullable, then enforce via code (or potentially, trigger functions) that exactly one of `value`/`something` was populated, then do some custom deserialization of your own.

Either way, this crate won't help you, sorry.
