### ISSUE TITLE
enums, sql_query and bind

### ISSUE THREAD

**Issue by jasonlor** [adwhit/diesel-derive-enum#41]
Does diesel-derive enum support binding an array of enums (i.e. Array<SampleType>, where SampleType is an enum derived by this crate) into a sql_query? I'm seeing the following compiler error with the following code.

```
let sample_array: Vec<SampleArray> = vec![SampleArray::One];

sql_query(include_str!("queries/test.sql"))
            .bind::<DieselUuid, _>(&sample_uuid)
            .bind::<DieselUuid, _>(&test_uuid)
            .bind::<Array<SampleType>, _>(&sample_array)
            .get_results(&cx.dbcon)?
```

``` ^^^^^^^^^^^ the trait `diesel::query_dsl::LoadQuery<_, _>` is not implemented for `diesel::query_builder::sql_query::UncheckedBind<diesel::query_builder::sql_query::UncheckedBind<diesel::query_builder::sql_query::UncheckedBind<diesel::query_builder::SqlQuery, &uuid::Uuid, diesel::sql_types::Uuid>, &uuid::Uuid, diesel::sql_types::Uuid>, &std::vec::Vec<models::sql_types::SampleType>, diesel::sql_types::Array<models::sql_types::SampleType>>```

**Comment by adwhit** [comment]
Sorry, no idea how `sql_query` works. If you can figure out the necessary trait impls, I would consider a PR.

**Comment by adwhit** [comment]
Just found the gitter comment that mentions this issue and a diesel maintainer mentioned that 

> diesel-derive-enum is not supported by the diesel team. As far as I'm aware they do miss some critical trait implementations.

So perhaps this issue does deserve more investigation.

**Comment by WeaponMan** [comment]
Just use instead of  `Array<SampleType>` this `Array<SampleTypeMapping>` and you good to go!
