### ISSUE TITLE
Enums in Postgres generate a request to every use of enum value

### ISSUE THREAD

**Issue by frol** [adwhit/diesel-derive-enum#52]
Using a remote DB @khorolets and I discovered that our requests are too slow (observed high latencies). Digging into it we learned that doing an insert of N records in a single query produce N pre-flight queries and they are related to the lookup:

https://github.com/adwhit/diesel-derive-enum/blob/731b86fec2afb39a255a59c564abe002c7f22e23/src/lib.rs#L273-L277

Logging out the looked up type we observe:

```rust
PgTypeMetadata { oid: 0, array_oid: 0 }
```

Thus, replacing the lookup call with the const value we avoid all the unrelated requests and our implementation seems to work just fine. It is hard to tell if this is reasonable to use this const instead of a dynamic lookup:

```rust
 impl HasSqlType<#diesel_mapping> for Pg { 
     fn metadata(lookup: &Self::MetadataLookup) -> Self::TypeMetadata { 
         Self::TypeMetadata { oid: 0, array_oid: 0 }
     } 
 } 
```

**UPD:** Our `CREATE TYPE` SQL migration had mismatching names with the enums in the source code, but even once we fixed the mismatch and started observing proper values (`PgTypeMetadata { oid: 21564, array_oid: 21563 }`), it did not change anything (still slow if we do this lookup every time). I wonder what is the use of these `oid` and `array_oid` values since SELECT (with and without filters), UPDATE, and INSERT operations succeed even if the metadata method always returns `Self::TypeMetadata { oid: 0, array_oid: 0 }`.

**Comment by frol** [comment]
I have no experience with `oid` and PostgreSQL enums, so I decided to raise an issue on diesel (https://github.com/diesel-rs/diesel/issues/2469) to gather more information about proper HasSqlType implementation.

**Comment by frol** [comment]
This seems to be resolved in the master branch of diesel (future 2.0 release, afaik) by an introduction of metadata caching (https://github.com/diesel-rs/diesel/pull/2088).

Useful comment about `oid` (https://github.com/diesel-rs/diesel/issues/2469#issuecomment-665007091):

> The dynamic lookup of the OID is required as OID's of custom types are not stable across different postgres instances. Just using 0 there will cause issues as soon as the exact type is required to be known by postgres. That's the case for example if you try to insert an array of values of your custom type.

**Comment by adwhit** [comment]
Hi, you've already resolved it but thanks for the bug report and I appreciate the investigation. I had no idea this was a problem.

**Comment by frol** [comment]
Also, worth mentioning the issue the caching revealed: https://github.com/diesel-rs/diesel/issues/2203

@adwhit Thank you for your work on this project. It helped us a lot to make our code straightforward and idiomatic!
