### ISSUE TITLE
Single word names

### ISSUE THREAD

**Issue by romixlab** [adwhit/diesel-derive-enum#54]
It seems that single word names like 'Flow' messes things up. I've created SQL type as:
```sql
CREATE TYPE flow AS ENUM ('credit_only', 'debit_only', 'debit_credit');
```

And corresponding enum as:
```rust
#[derive(Debug, PartialEq, DbEnum)]
pub enum Flow {
    CreditOnly,
    DebitOnly,
    DebitCredit
}
```

Build failed with `AsExpression` trait was not satisfied. But after I renamed it to 'account_flow' and added `#[DieselType = "Account_flow"]` to the enum, everything compiled just fine. Maybe not the best idea to name types like that, but error messages where quite confusing.

**Comment by adwhit** [comment]
It definitely work with the way you have written it. Did you perhaps miss off the `Mapping` part in your schema? i.e. `FlowMapping`

**Comment by danjenson** [comment]
I think the problem is that diesel cli with `print-schema` maps single words like `Flow -> Flow` rather than `Flow -> FlowMapping`, and when you specify `#[DieselType = "Flow"]` above `pub enum Flow`, you get an error

**Comment by romixlab** [comment]
Well this is way over my knowledge of Diesel to actually do something, so I think I will close it then.
