### ISSUE TITLE
Sqlite support?

### ISSUE THREAD

**Issue by Boscop** [adwhit/diesel-derive-enum#6]
Does it work with sqlite too? As described here: https://github.com/diesel-rs/diesel/issues/343#issuecomment-243406640

**Comment by adwhit** [comment]
Good question. It won't work as-is because the impls are specifically for Pg. But it looks like it might only be a simple refactor to add a `#[derive(SqliteEnum)]` too

**Comment by Boscop** [comment]
Nice, I'm looking forward to using this crate with Sqlite :)
