### ISSUE TITLE
Missing trait impls with Diesel 1.4.8 and Postgres

### ISSUE THREAD

**Issue by benthillerkus** [adwhit/diesel-derive-enum#68]
I made an example repo to show the issue: [benthillerkus/diesel-enum-trouble](https://github.com/benthillerkus/diesel-enum-trouble).

**Comment by adwhit** [comment]
Please take a look at https://github.com/adwhit/diesel-derive-enum/issues/62, your fix is the same

**Comment by benthillerkus** [comment]
Thank you
