### ISSUE TITLE
Any chance this could be merged into diesel itself?

### ISSUE THREAD

**Issue by ZelCloud** [adwhit/diesel-derive-enum#69]
I'm sorry if this has been asked somewhere already, but would it be possible for this to be merged into diesel? Instead of living as a separate crate.

**Comment by adwhit** [comment]
This is not an official crate and I cannot speak for the `diesel` authors, but it seems they decided against it - see https://github.com/diesel-rs/diesel/issues/343

**Comment by ZelCloud** [comment]
Thanks for the answer @adwhit, its unfortunate the Diesel authors don't want to add this kind of support directly within diesel. 

Closing the issue since nothing can be done from this end.
