### ISSUE TITLE
migrations + sqlite

### ISSUE THREAD

**Issue by dom96** [adwhit/diesel-derive-enum#74]
It seems for the likes of Postgres Diesel will generate appropriate types for enums, as described in https://github.com/adwhit/diesel-derive-enum/issues/43. But what about when I am using Sqlite? i.e.

```
CREATE TABLE PriceMetadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  category TEXT CHECK(category IN ('A', 'B', 'C')) NOT NULL,
  data TEXT NOT NULL
)
```

Is there anything I can do other than using `patch_file` to replace the `Text` in my schema.rs?

**Comment by adwhit** [comment]
Hi, sorry I think your question is best directed at the main diesel repository - this library is 'unofficial' and we can't change way diesel handles migrations.

But in answer to your question - I believe the answer is no, and a patch is the way to go.
