### ISSUE TITLE
Release 2.0-rc0 version to crates.io

### ISSUE THREAD

**Issue by oeed** [adwhit/diesel-derive-enum#75]
Now that master is supporting 2.0-rc0 it'd be nice if a version targeting 2.0 could be released on crates.io, rather than needing a git ref. https://github.com/quodlibetor/diesel-derive-newtype is doing that, for example.

**Comment by adwhit** [comment]
Yes, I've been looking into doing this. What is making me hesitate is the API for this crate has changed for `2.0` and I'm not sure it is right. We now how two different annotations for the enum, `DieselExistingType = ...` for postgres and `DieselType = ...` for mysql/sqlite and I think it's a bit confusing. Thinking I could combine them into one, but maybe that would be even more confusing?

**Comment by sassman** [comment]
Now also diesel has it's version `2.0.0-rc.0` out on crates.io.
So having a compatible version of `diesel-derive-enum` maybe as well named like `2.0.0-rc.0` would be very consistent and helpful.
