### ISSUE TITLE
DbEnum macro results in "unresolved import"

### ISSUE THREAD

**Issue by buehler** [adwhit/diesel-derive-enum#76]
Hey there

I try to use the derive enum macro with diesel master (2.0.0-rc.0) but when trying to define an enum, the compiler complains about an unresolved import:

```rust
use diesel::prelude::*;
use diesel_derive_enum::*;

#[derive(Debug, PartialEq, DbEnum)]
#[DieselType = "LanguageEnum"]
#[PgType = "language"]
pub enum Language {
    De,
    Fr,
    It,
    En,
}
```

When trying to use this enum above, the compiler returns:
```
246 | #[derive(Debug, PartialEq, DbEnum)]
    |                            ^^^^^^
    |                            |
    |                            unresolved import
    |                            help: a similar path exists: `crate::database::schema`
```

Could someone point me into the right direction?

**Comment by adwhit** [comment]
Mmm the README is now out-of-sync with the master branch, I need to get around to updating it.
The TLDR is you have to specify `DieselExistingType` not `DieselType`, see: https://github.com/adwhit/diesel-derive-enum/blob/e6aa69856245f083645a0087527236a6bff42c18/src/lib.rs#L17
