### ISSUE TITLE
`could not find sql_types in schema` on every `DBEnum`

### ISSUE THREAD

**Issue by ekkaiasmith** [adwhit/diesel-derive-enum#82]
Every time DBEnum is used, an error "could not find `sql_types` in `schema`" appears.

**My config:**

- `diesel = { version = "2.0.0", features = ["postgres", "r2d2", "chrono", "uuid", "serde_json"] }` with Diesel-CLI 2.0.0
- `diesel-derive-enum = { version = "2.0.0-rc.0", features = ["postgres"] }`

**Comment by adwhit** [comment]
Try deleting and recrating your schema, the `print-schema` macro should pick up the enum types in your database
