### ISSUE TITLE
Changes in 2.0.0

### ISSUE THREAD

**Issue by ayrat555** [adwhit/diesel-derive-enum#88]
It seems 2.0.0 has some breaking compared to 2.0.0-rc.0

Would it be possible to include them and upgrade instructions  in the Changelog file

@adwhit

**Comment by adwhit** [comment]
I will try to update the README but AFAIK the only break since `2.0.0-rc.0` is that if you were using postgres with diesel-cli, you now *must* annotate your enum with `ExistingTypePath`, whereas before it was optional.
