### ISSUE TITLE
conflicting implementation for `schema::sql_types::MyType` (first implementation in schema.rs)

### ISSUE THREAD

**Issue by tpkee** [adwhit/diesel-derive-enum#91]
Hi!
Whenever I try to derive a DbEnum trait for my MyType enum, I get that error. It seems that DbEnum implements `diesel::query_builder::QueryId`, but it is also derived by default when using the diesel-cli.

**Comment by tpkee** [comment]
`diesel = "2.1"`

**Comment by adwhit** [comment]
Thanks. This will be the problem discussed here: https://github.com/adwhit/diesel-derive-enum/issues/10#issuecomment-1434557350
Until I get a fix out, the workaround is to downgrade to `diesel = "2.0.*"`

**Comment by adwhit** [comment]
This is now fixed in `2.1.0`.

Unfortunately it's a breaking change for anyone running `cargo update`. Couldn't be avoided, due to upstream changes.
