### ISSUE TITLE
Uppercase enum variants fails to serialize

### ISSUE THREAD

**Issue by madser123** [adwhit/diesel-derive-enum#97]
I had some issues setting this up, as the crate fails to serialize UPPERCASE enum variants properly.

Here is the code that fails:

SQL:
```sql
CREATE TYPE user_type_enum AS ENUM (
    'BOT',
    'USER'
);
```

Rust:
```rust
#[derive(Debug, Clone, DbEnum, Serialize, Deserialize)]
#[ExistingTypePath = "crate::schema::sql_types::UserTypeEnum"]
pub enum Type {
    #[serde(rename = "BOT")]
    BOT,

    #[serde(rename = "USER")]
    USER,
}
```

The enum also fails with variant names `Bot` and `User`.

The error output is: `DeserializationError("Unrecognized enum variant: 'BOT'")`

After changing the code to the following, it works:

SQL:
```sql
CREATE TYPE user_type_enum AS ENUM (
    'bot',
    'user'
);
```

Rust:
```rust
#[derive(Debug, Clone, DbEnum, Serialize, Deserialize)]
#[ExistingTypePath = "crate::schema::sql_types::UserTypeEnum"]
pub enum Type {
    #[serde(rename = "bot")]
    Bot,

    #[serde(rename = "user")]
    User,
}
```

I would expect the crate to handle the uppercase enum variants without failing.

**Comment by adwhit** [comment]
This crate does not use serde, so your annotations have no effect. As described in the README, this crate assumes `snake_case` enum names by default. You need to add `#[DbValueStyle = "UPPERCASE"]` to get the behaviour you want.
